# Generated by Django 4.2.5 on 2023-09-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pornapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av', models.BooleanField(default=False)),
                ('pics', models.ImageField(upload_to='Gallery')),
                ('types', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('des', models.TextField()),
            ],
        ),
    ]
